/* Lophera Studio V6 — clientes, pedidos e cupons */
(function(){const $=id=>document.getElementById(id),money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),safe=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
window.loadCustomers=async()=>{const{data,error}=await supabaseClient.from('customer_profiles').select('*').order('created_at',{ascending:false});if(error)return $('customersList').innerHTML='<div class="empty">Erro: '+safe(error.message)+'</div>';const profiles=data||[];const{data:orders}=await supabaseClient.from('orders').select('id,customer_id,total,created_at');$('customersList').innerHTML=profiles.map(p=>{const os=(orders||[]).filter(o=>o.customer_id===p.user_id),spent=os.reduce((a,o)=>a+Number(o.total||0),0);return `<div class="category-row"><div><b>${safe(p.full_name||'Cliente')}</b><span>${safe(p.phone||'Sem telefone')} · ${os.length} pedido(s) · ${money(spent)}</span><span>${safe([p.city,p.state].filter(Boolean).join(' / '))}</span></div><button class="btn" onclick="editCustomer('${p.user_id}')">Ver / editar</button></div>`}).join('')||'<div class="empty">Nenhum cliente cadastrado ainda.</div>'};
window.editCustomer=async id=>{const{data:p,error}=await supabaseClient.from('customer_profiles').select('*').eq('user_id',id).single();if(error)return alert(error.message);$('customerEditor').innerHTML=`<form class="form wide-form" onsubmit="saveCustomer(event,'${id}')"><h3>${safe(p.full_name||'Cliente')}</h3><div class="form-two"><label>Nome<input id="c_name" value="${safe(p.full_name)}"></label><label>Telefone<input id="c_phone" value="${safe(p.phone)}"></label></div><div class="form-two"><label>CPF<input id="c_cpf" value="${safe(p.cpf)}"></label><label>Nascimento<input id="c_birth" type="date" value="${safe(p.birth_date)}"></label></div><div class="form-two"><label>CEP<input id="c_zip" value="${safe(p.zip_code)}"></label><label>Cidade<input id="c_city" value="${safe(p.city)}"></label></div><label>Endereço<input id="c_address" value="${safe(p.address)}"></label><div class="form-two"><label>Número<input id="c_number" value="${safe(p.address_number)}"></label><label>Bairro<input id="c_neighborhood" value="${safe(p.neighborhood)}"></label></div><div class="form-two"><label>Complemento<input id="c_complement" value="${safe(p.complement)}"></label><label>UF<input id="c_state" value="${safe(p.state)}" maxlength="2"></label></div><label>Referência<input id="c_reference" value="${safe(p.reference_point)}"></label><p class="muted">A senha do cliente nunca fica visível no Studio.</p><button class="btn solid">Salvar dados</button></form>`};
window.saveCustomer=async(e,id)=>{e.preventDefault();const v=x=>$(x).value||null;const payload={full_name:v('c_name'),phone:v('c_phone'),cpf:v('c_cpf'),birth_date:v('c_birth'),zip_code:v('c_zip'),city:v('c_city'),address:v('c_address'),address_number:v('c_number'),neighborhood:v('c_neighborhood'),complement:v('c_complement'),state:v('c_state'),reference_point:v('c_reference'),updated_at:new Date().toISOString()};const{error}=await supabaseClient.from('customer_profiles').update(payload).eq('user_id',id);if(error)return alert(error.message);alert('Cliente atualizado ♡');loadCustomers()};
window.loadOrdersAdmin=async()=>{const{data,error}=await supabaseClient.from('orders').select('*,order_items(*)').order('created_at',{ascending:false});if(error)return $('ordersList').innerHTML='<div class="empty">Erro: '+safe(error.message)+'</div>';$('ordersList').innerHTML=(data||[]).map(o=>`<div class="setting-card"><div class="small">PEDIDO #${o.id}</div><h3>${money(o.total)}</h3><p>${new Date(o.created_at).toLocaleString('pt-BR')} · ${safe(o.status)}</p><p>${(o.order_items||[]).map(i=>safe(i.product_name)+' × '+i.quantity).join('<br>')}</p><div class="form-two"><label>Status<select id="os_${o.id}">${['aguardando_atendimento','aguardando_pagamento','pagamento_confirmado','em_producao','preparando_envio','enviado','saiu_para_entrega','entregue','cancelado'].map(s=>`<option ${o.status===s?'selected':''}>${s}</option>`).join('')}</select></label><label>Rastreio<input id="ot_${o.id}" value="${safe(o.tracking_code)}"></label></div><button class="btn solid" onclick="saveOrderAdmin(${o.id})">Salvar pedido</button></div>`).join('')||'<div class="empty">Nenhum pedido ainda.</div>'};
window.queueOrderForErp=async id=>{const{error}=await supabaseClient.rpc('admin_queue_order_for_erp',{p_order_id:id});if(error)return alert(error.message);alert('Pedido '+salesOrderNumber(id)+' preparado para o ERP ♡');await loadOrdersAdmin()};
window.saveOrderAdmin=async id=>{const{error}=await supabaseClient.from('orders').update({status:$('os_'+id).value,tracking_code:$('ot_'+id).value||null}).eq('id',id);if(error)return alert(error.message);alert('Pedido atualizado ♡');loadOrdersAdmin()};
window.loadCoupons=async()=>{const{data,error}=await supabaseClient.from('coupons').select('*').order('created_at',{ascending:false});if(error)return;$('couponsList').innerHTML=(data||[]).map(c=>`<div class="category-row"><div><b>${safe(c.code)}</b><span>${c.discount_type==='percent'?c.discount_value+'%':money(c.discount_value)} · mínimo ${money(c.min_order_value)} · ${c.active?'Ativo':'Inativo'} · usados ${c.used_count} · limite geral: ${c.max_uses??'ilimitado'} · por pessoa: ${c.per_user_limit??'ilimitado'}</span></div><button class="btn" onclick="toggleCoupon(${c.id},${!c.active})">${c.active?'Desativar':'Ativar'}</button></div>`).join('')||'<div class="empty">Nenhum cupom.</div>'};
window.createCoupon=async e=>{e.preventDefault();const payload={code:$('cp_code').value.trim().toUpperCase(),discount_type:$('cp_type').value,discount_value:Number($('cp_value').value),min_order_value:Number($('cp_min').value||0),max_uses:$('cp_max').value?Number($('cp_max').value):null,per_user_limit:$('cp_user_max').value?Number($('cp_user_max').value):null,expires_at:$('cp_exp').value?new Date($('cp_exp').value+'T23:59:59').toISOString():null,active:true};const{error}=await supabaseClient.from('coupons').insert(payload);if(error)return alert(error.message);e.target.reset();loadCoupons();alert('Cupom criado ♡')};window.toggleCoupon=async(id,active)=>{const{error}=await supabaseClient.from('coupons').update({active}).eq('id',id);if(error)return alert(error.message);loadCoupons()};
function ensureSalesStyles(){
  if(document.getElementById('lophera-sales-style'))return;
  const s=document.createElement('style');s.id='lophera-sales-style';s.textContent=`
  .sales-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin:0 0 18px}
  .sales-kpi{background:#fff;border:1px solid #e3d7e6;padding:18px;border-radius:10px}.sales-kpi span{display:block;font-size:10px;letter-spacing:1.5px;text-transform:uppercase;color:#8a748f}.sales-kpi b{display:block;font:500 30px 'Cormorant Garamond',serif;margin-top:6px;color:#4d3157}
  .sales-tools{display:flex;gap:10px;flex-wrap:wrap;margin:0 0 18px}.sales-tools input,.sales-tools select{border:1px solid #d9cbdc;background:#fff;padding:10px 12px;min-height:42px}.sales-tools input{flex:1;min-width:230px}
  .sales-order{background:#fff;border:1px solid #e2d7e5;border-radius:12px;margin-bottom:16px;overflow:hidden}.sales-order-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;padding:18px 20px;background:#faf7fb;border-bottom:1px solid #eee5f0}.sales-order-head h3{font:500 28px 'Cormorant Garamond',serif;margin:2px 0 4px}.sales-order-head .status-pill{font-size:10px;letter-spacing:1px;text-transform:uppercase;padding:7px 10px;border:1px solid #cdb9d3;border-radius:999px;white-space:nowrap;background:#fff}
  .sales-order-grid{display:grid;grid-template-columns:1.3fr .9fr;gap:0}.sales-block{padding:18px 20px;border-right:1px solid #eee5f0}.sales-block:last-child{border-right:0}.sales-block h4{margin:0 0 12px;font-size:11px;letter-spacing:1.5px;text-transform:uppercase;color:#775c80}.sales-customer{font-size:12px;line-height:1.8;color:#55495a}
  .sales-item{display:grid;grid-template-columns:58px 1fr auto;gap:12px;align-items:center;padding:10px 0;border-bottom:1px solid #f0eaf1}.sales-item:last-child{border-bottom:0}.sales-item img{width:58px;height:58px;object-fit:cover;background:#f3edf4}.sales-item b{display:block;font-size:12px}.sales-item small{display:block;color:#7c6c80;line-height:1.6}.sales-item strong{font-size:12px;text-align:right}
  .sales-edit{padding:18px 20px;background:#fcfafc;border-top:1px solid #eee5f0}.sales-edit-grid{display:grid;grid-template-columns:1.2fr 1fr 1fr 1fr;gap:10px}.sales-edit label{font-size:10px;letter-spacing:.7px}.sales-edit input,.sales-edit select{width:100%;margin-top:5px;padding:9px;border:1px solid #d9cbdc;background:#fff}.sales-meta{font-size:10px;color:#817484;line-height:1.8;margin-top:10px}
  @media(max-width:900px){.sales-kpis{grid-template-columns:1fr 1fr}.sales-order-grid{grid-template-columns:1fr}.sales-block{border-right:0;border-bottom:1px solid #eee5f0}.sales-edit-grid{grid-template-columns:1fr 1fr}}
  @media(max-width:560px){.sales-kpis{grid-template-columns:1fr}.sales-order-head{flex-direction:column}.sales-edit-grid{grid-template-columns:1fr}.sales-item{grid-template-columns:50px 1fr}.sales-item strong{grid-column:2;text-align:left}}
  `;document.head.appendChild(s);
}
const salesStatusLabels={aguardando_pagamento:'Aguardando pagamento',pago:'Pago',emitido_nota:'Emitido nota',em_transporte:'Em transporte',entregue:'Entregue',cancelado:'Cancelado',pagamento_falhou:'Pagamento falhou',reembolsado:'Reembolsado',contestado:'Contestado'};
let salesOrdersCache=[];
function salesOrderNumber(id){return 'LP-'+String(id).padStart(6,'0')}
function salesAddress(o){const a=o.shipping_address||{},p=o.customer||{};const parts=[a.address||a.street||p.address,a.number||a.address_number||p.address_number,a.complement||p.complement,a.neighborhood||p.neighborhood,[a.city||p.city,a.state||p.state].filter(Boolean).join('/'),a.zip_code||a.cep||p.zip_code].filter(Boolean);return parts.join(' · ')}
function renderSalesOrders(){
  ensureSalesStyles();
  const list=$('ordersList');if(!list)return;
  const q=($('salesSearch')?.value||'').trim().toLowerCase(),st=$('salesStatusFilter')?.value||'all';
  const arr=salesOrdersCache.filter(o=>{const blob=[salesOrderNumber(o.id),o.customer_email,o.customer?.full_name,o.customer?.cpf,...(o.items||[]).flatMap(i=>[i.product_name,i.sku,i.color,i.size])].join(' ').toLowerCase();return(!q||blob.includes(q))&&(st==='all'||o.status===st)});
  const paid=salesOrdersCache.filter(o=>o.payment_status==='pago');const revenue=paid.reduce((a,o)=>a+Number(o.total||0),0);const awaiting=salesOrdersCache.filter(o=>o.status==='aguardando_pagamento').length;const shipping=salesOrdersCache.filter(o=>['emitido_nota','em_transporte'].includes(o.status)).length;
  const kpis='<div class="sales-kpis"><div class="sales-kpi"><span>Vendas pagas</span><b>'+paid.length+'</b></div><div class="sales-kpi"><span>Faturamento pago</span><b>'+money(revenue)+'</b></div><div class="sales-kpi"><span>Aguardando pagamento</span><b>'+awaiting+'</b></div><div class="sales-kpi"><span>Em expedição</span><b>'+shipping+'</b></div></div>';
  const tools='<div class="sales-tools"><input id="salesSearch" placeholder="Buscar pedido, cliente, CPF, produto ou SKU..." value="'+safe($('salesSearch')?.value||'')+'" oninput="renderSalesOrders()"><select id="salesStatusFilter" onchange="renderSalesOrders()"><option value="all">Todos os status</option>'+Object.entries(salesStatusLabels).map(([v,l])=>'<option value="'+v+'" '+(st===v?'selected':'')+'>'+l+'</option>').join('')+'</select></div>';
  const cards=arr.map(o=>{const p=o.customer||{},addr=salesAddress(o),items=o.items||[];return '<article class="sales-order"><div class="sales-order-head"><div><div class="small">PEDIDO '+salesOrderNumber(o.id)+'</div><h3>'+money(o.total)+'</h3><div class="sales-meta">'+new Date(o.created_at).toLocaleString('pt-BR')+(o.paid_at?' · Pago em '+new Date(o.paid_at).toLocaleString('pt-BR'):'')+'</div></div><span class="status-pill">'+safe(salesStatusLabels[o.status]||o.status)+'</span></div><div class="sales-order-grid"><div class="sales-block"><h4>Itens comprados</h4>'+items.map(i=>'<div class="sales-item">'+(i.image_url?'<img src="'+safe(i.image_url)+'">':'<div></div>')+'<div><b>'+safe(i.product_name)+'</b><small>SKU: <strong>'+safe(i.sku||'Sem SKU')+'</strong><br>'+safe([i.color,i.size].filter(Boolean).join(' · '))+' · Qtd. '+i.quantity+'</small></div><strong>'+money(Number(i.unit_price||0)*Number(i.quantity||0))+'</strong></div>').join('')+'</div><div class="sales-block"><h4>Cliente e envio</h4><div class="sales-customer"><b>'+safe(p.full_name||'Cliente')+'</b><br>'+safe(o.customer_email||'Sem e-mail')+'<br>'+safe(p.phone||'Sem telefone')+(p.cpf?'<br>CPF: '+safe(p.cpf):'')+'<br><br><b>Endereço</b><br>'+safe(addr||'Endereço ainda não informado')+'</div></div></div><div class="sales-edit"><div class="sales-edit-grid"><label>Andamento<select id="os_'+o.id+'">'+['aguardando_pagamento','pago','emitido_nota','em_transporte','entregue','cancelado'].map(s=>'<option value="'+s+'" '+(o.status===s?'selected':'')+'>'+salesStatusLabels[s]+'</option>').join('')+'</select></label><label>Nº da nota<input id="oinv_'+o.id+'" value="'+safe(o.invoice_number||'')+'" placeholder="NF-e"></label><label>Rastreio<input id="ot_'+o.id+'" value="'+safe(o.tracking_code||'')+'" placeholder="Código"></label><label>Link rastreio<input id="otu_'+o.id+'" value="'+safe(o.tracking_url||'')+'" placeholder="https://..."></label></div><div class="sales-meta">Pagamento: '+safe(o.payment_status||'pendente')+(o.provider_payment_id?' · Mercado Pago #'+safe(o.provider_payment_id):'')+(o.erp_order_id?' · ERP #'+safe(o.erp_order_id):'')+' · Sync ERP: '+safe(o.erp_sync_status||'not_sent')+(o.erp_last_error?' · erro: '+safe(o.erp_last_error):'')+'</div><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:12px"><button class="btn solid" onclick="saveOrderAdmin('+o.id+')">Salvar andamento</button><button class="btn" onclick="queueOrderForErp('+o.id+')">↗ Enviar ao ERP</button><button class="btn" onclick="sendOrderUpdateEmail('+o.id+')">✉ Enviar atualização</button></div></div></article>'}).join('');
  list.innerHTML=kpis+tools+(cards||'<div class="empty">Nenhum pedido encontrado.</div>');
}
window.renderSalesOrders=renderSalesOrders;
window.loadOrdersAdmin=async()=>{ensureSalesStyles();const list=$('ordersList');if(list)list.innerHTML='<div class="empty">Carregando vendas...</div>';const{data,error}=await supabaseClient.rpc('get_admin_sales_orders');if(error){if(list)list.innerHTML='<div class="empty">Erro: '+safe(error.message)+'</div>';return}salesOrdersCache=Array.isArray(data)?data:[];renderSalesOrders()};
window.saveOrderAdmin=async id=>{const{error}=await supabaseClient.rpc('admin_update_order_sales',{p_order_id:id,p_status:$('os_'+id).value,p_tracking_code:$('ot_'+id).value||null,p_tracking_url:$('otu_'+id).value||null,p_invoice_number:$('oinv_'+id).value||null});if(error)return alert(error.message);alert('Pedido '+salesOrderNumber(id)+' atualizado ♡');await loadOrdersAdmin()};
})();