/* Lophera Studio V7.1 — nova Lophera como site principal + mobile preview */
(function(){
 const TEST_ROOT='teste-lophera/';
 window.previewPage=function(page,b){
   const clean=String(page||'index.html').replace(/^\.\//,'');
   const target=clean.startsWith(TEST_ROOT)?clean:(['index.html','loja.html','sobre.html'].includes(clean)?TEST_ROOT+clean:clean);
   const frame=document.getElementById('sitePreview');
   if(frame)frame.src=target+'?adminPreview=1&t='+Date.now();
   const label=document.getElementById('previewUrl');
   if(label)label.textContent='lophera.com.br/'+target.replace(/^teste-lophera\//,'');
   document.querySelectorAll('.v3-pagebuttons .chip').forEach(x=>x.classList.remove('active'));b?.classList.add('active');
 };
 window.setPreviewDevice=function(device,btn){const frame=document.getElementById('sitePreview'),wrap=document.querySelector('.browser-frame');if(!frame||!wrap)return;document.querySelectorAll('.device-switch .chip').forEach(x=>x.classList.remove('active'));btn?.classList.add('active');wrap.classList.toggle('preview-mobile',device==='mobile');wrap.classList.toggle('preview-desktop',device!=='mobile');const note=document.getElementById('deviceNote');if(note)note.textContent=device==='mobile'?'Prévia Celular · 390 px — mesmo site, proporções mobile':'Prévia PC · largura completa';try{installVisualEditor()}catch(e){}};
 function addTab(side,label,id,loader){const b=document.createElement('button');b.className='side-link';b.textContent=label;b.onclick=()=>{showTab(id,b);loader?.()};side.appendChild(b)}
 document.addEventListener('DOMContentLoaded',()=>{
   const fix=document.createElement('script');fix.src='admin-preview-fix.js?v=3';document.head.appendChild(fix);
   const topLink=document.querySelector('.v3-top-actions a.btn');if(topLink)topLink.href=TEST_ROOT+'index.html';
   const frame=document.getElementById('sitePreview');if(frame)frame.src=TEST_ROOT+'index.html?adminPreview=1&t='+Date.now();
   const previewUrl=document.getElementById('previewUrl');if(previewUrl)previewUrl.textContent='lophera.com.br/';
   const bar=document.querySelector('#tab-editor .v3-pagebar');if(bar&&!document.querySelector('.device-switch')){const d=document.createElement('div');d.className='device-switch';d.innerHTML='<span id="deviceNote">Prévia PC · largura completa</span><div><button class="chip active" onclick="setPreviewDevice(\'desktop\',this)">▣ PC</button><button class="chip" onclick="setPreviewDevice(\'mobile\',this)">▯ Celular</button></div>';bar.insertAdjacentElement('afterend',d);document.querySelector('.browser-frame')?.classList.add('preview-desktop')}
   const script=document.createElement('script');script.src='admin-v6.js?v=7.1';script.onload=()=>{const side=document.querySelector('.v3-sidebar'),main=document.querySelector('.v3-main');if(!side||!main)return;const title=document.createElement('div');title.className='v3-side-title';title.textContent='OPERAÇÃO';side.appendChild(title);addTab(side,'👤 Clientes','customers',loadCustomers);addTab(side,'📦 Pedidos','orders',loadOrdersAdmin);addTab(side,'🎟 Cupons','coupons',loadCoupons);main.insertAdjacentHTML('beforeend',`<section id="tab-customers" class="admin-tab" style="display:none"><div class="v3-pagebar"><div><div class="small">CRM</div><h2>Clientes</h2><p>Dados de suporte. Senhas nunca são exibidas.</p></div><button class="btn" onclick="loadCustomers()">↻ Atualizar</button></div><div class="product-manager"><div id="customersList" class="category-list"></div><div id="customerEditor" class="product-drawer"><div class="drawer-empty">Selecione um cliente.</div></div></div></section><section id="tab-orders" class="admin-tab" style="display:none"><div class="v3-pagebar"><div><div class="small">VENDAS</div><h2>Pedidos</h2></div><button class="btn" onclick="loadOrdersAdmin()">↻ Atualizar</button></div><div id="ordersList" class="settings-grid"></div></section><section id="tab-coupons" class="admin-tab" style="display:none"><div class="v3-pagebar"><div><div class="small">MARKETING</div><h2>Cupons</h2></div></div><form class="form wide-form" onsubmit="createCoupon(event)"><div class="form-two"><label>Código<input id="cp_code" required placeholder="LANCAMENTO10"></label><label>Tipo<select id="cp_type"><option value="percent">Porcentagem (%)</option><option value="fixed">Valor (R$)</option></select></label></div><div class="form-two"><label>Desconto<input id="cp_value" type="number" step=".01" min=".01" required></label><label>Compra mínima R$<input id="cp_min" type="number" step=".01" value="0"></label></div><div class="form-two"><label>Limite de usos<input id="cp_max" type="number" min="1"></label><label>Validade<input id="cp_exp" type="date"></label></div><button class="btn solid">+ Criar cupom</button></form><div id="couponsList" class="category-list" style="margin-top:25px"></div></section>`)};document.head.appendChild(script)
 });
})();