/* Lophera Studio V7.9 — carrinhos */
(function(){
const $=id=>document.getElementById(id),safe=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m])),money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
let cache=[];
function ago(iso){if(!iso)return '—';const m=Math.floor(Math.max(0,Date.now()-new Date(iso).getTime())/60000);if(m<1)return 'menos de 1 min';if(m<60)return m+' min';const h=Math.floor(m/60);if(h<24)return h+'h '+m%60+'min';const d=Math.floor(h/24);return d+' dia'+(d===1?'':'s')+' '+h%24+'h'}
function ensure(){
 if($('tab-carts'))return true;
 const side=document.querySelector('.v3-sidebar'),main=document.querySelector('.v3-main');if(!side||!main)return false;
 const orderBtn=[...side.querySelectorAll('.side-link')].find(b=>b.textContent.includes('Pedidos e vendas'));if(!orderBtn)return false;
 const b=document.createElement('button');b.className='side-link';b.textContent='🛒 Carrinhos';b.onclick=()=>{showTab('carts',b);loadCarts()};orderBtn.insertAdjacentElement('afterend',b);
 main.insertAdjacentHTML('beforeend','<section id="tab-carts" class="admin-tab" style="display:none"><div class="v3-pagebar"><div><div class="small">VENDAS</div><h2>Carrinhos</h2><p>Acompanhe carrinhos ativos e abandonados e envie lembretes.</p></div><button class="btn" onclick="loadCarts()">↻ Atualizar</button></div><div id="cartAdminList"></div></section>');
 const s=document.createElement('style');s.textContent='.cart-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:16px}.cart-kpi,.cart-card{background:#fff;border:1px solid #e3d7e6;border-radius:10px;padding:16px}.cart-kpi span{display:block;font-size:9px;color:#857287;text-transform:uppercase;letter-spacing:1px}.cart-kpi b{display:block;font:500 28px "Cormorant Garamond",serif;color:#4d3157;margin-top:5px}.cart-tools{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:14px}.cart-tools input,.cart-tools select{padding:10px;border:1px solid #d9cbdc;background:#fff}.cart-tools input{flex:1;min-width:220px}.cart-card{margin-bottom:12px}.cart-head{display:flex;justify-content:space-between;gap:10px}.cart-head h3{font:500 25px "Cormorant Garamond",serif;margin:2px 0}.cart-badge2{font-size:9px;padding:6px 9px;border-radius:99px;background:#eaf4ec;color:#447052}.cart-badge2.ab{background:#f8e7eb;color:#8d4154}.cart-item{display:grid;grid-template-columns:50px 1fr auto;gap:10px;align-items:center;padding:9px 0;border-top:1px solid #f0eaf1}.cart-item img{width:50px;height:50px;object-fit:cover}.cart-item b,.cart-item strong{font-size:11px}.cart-item small,.cart-meta{font-size:9px;color:#7f7183;line-height:1.6}.cart-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.cart-actions .btn[disabled]{opacity:.45;cursor:not-allowed}@media(max-width:700px){.cart-kpis{grid-template-columns:1fr 1fr}.cart-head{flex-direction:column}}';document.head.appendChild(s);return true;
}
function render(){
 const root=$('cartAdminList');if(!root)return;const q=($('cartSearch')?.value||'').toLowerCase(),f=$('cartFilter')?.value||'all';
 const list=cache.filter(c=>{const blob=[c.customer_name,c.customer_email,...(c.items||[]).map(i=>i.name)].join(' ').toLowerCase();return(!q||blob.includes(q))&&(f==='all'||(f==='ab'&&c.abandoned)||(f==='email'&&c.customer_email)||(f==='active'&&!c.abandoned))});
 const abandoned=cache.filter(c=>c.abandoned).length,withEmail=cache.filter(c=>c.customer_email).length,total=cache.reduce((a,c)=>a+Number(c.subtotal||0),0);
 const k='<div class="cart-kpis"><div class="cart-kpi"><span>Com itens</span><b>'+cache.length+'</b></div><div class="cart-kpi"><span>Abandonados</span><b>'+abandoned+'</b></div><div class="cart-kpi"><span>Com e-mail</span><b>'+withEmail+'</b></div><div class="cart-kpi"><span>Valor</span><b>'+money(total)+'</b></div></div>';
 const tools='<div class="cart-tools"><input id="cartSearch" placeholder="Buscar cliente ou produto..." value="'+safe($('cartSearch')?.value||'')+'" oninput="renderCarts()"><select id="cartFilter" onchange="renderCarts()"><option value="all">Todos</option><option value="ab" '+(f==='ab'?'selected':'')+'>Abandonados (30+ min)</option><option value="active" '+(f==='active'?'selected':'')+'>Ativos</option><option value="email" '+(f==='email'?'selected':'')+'>Com e-mail</option></select></div>';
 const cards=list.map(c=>{const recent=!c.last_reminder_at||Date.now()-new Date(c.last_reminder_at).getTime()>=43200000,can=!!c.customer_email&&recent;return '<article class="cart-card"><div class="cart-head"><div><div class="small">CARRINHO</div><h3>'+safe(c.customer_name||'Visitante')+'</h3><div class="cart-meta">'+safe(c.customer_email||'Visitante ainda sem e-mail')+' · criado há '+ago(c.first_item_at||c.created_at)+' · última atividade há '+ago(c.last_activity_at)+'</div></div><span class="cart-badge2 '+(c.abandoned?'ab':'')+'">'+(c.abandoned?'Abandonado':c.status==='checkout'?'No checkout':'Ativo')+'</span></div><div>'+((c.items||[]).map(i=>'<div class="cart-item">'+(i.image?'<img src="'+safe(i.image)+'">':'<div></div>')+'<div><b>'+safe(i.name)+'</b><small>'+safe([i.color,i.size].filter(Boolean).join(' · '))+' · '+Number(i.qty||1)+' un.<br>No carrinho há '+ago(i.added_at||c.first_item_at)+'</small></div><strong>'+money(Number(i.price||0)*Number(i.qty||1))+'</strong></div>').join(''))+'</div><div class="cart-meta"><b>Total: '+money(c.subtotal)+'</b> · '+(c.last_reminder_at?'último lembrete há '+ago(c.last_reminder_at):'nenhum lembrete enviado')+'</div><div class="cart-actions"><button class="btn solid" '+(can?'':'disabled')+' onclick="sendCartReminder(\''+c.id+'\')">'+(c.customer_email?'✉ Enviar lembrete':'Sem e-mail')+'</button><a class="btn" target="_blank" href="https://lopherastore.com.br/loja.html?restore_cart='+encodeURIComponent(c.restore_token)+'">Abrir carrinho ↗</a></div></article>'}).join('');
 root.innerHTML=k+tools+(cards||'<div class="empty">Nenhum carrinho encontrado.</div>');
}
window.renderCarts=render;
window.loadCarts=async()=>{if(!ensure())return;const root=$('cartAdminList');root.innerHTML='<div class="empty">Carregando...</div>';const{data,error}=await supabaseClient.rpc('get_admin_carts');if(error){root.innerHTML='<div class="empty">Erro: '+safe(error.message)+'</div>';return}cache=Array.isArray(data)?data:[];render()};
window.sendCartReminder=async id=>{const c=cache.find(x=>x.id===id);if(!c?.customer_email)return alert('Esse carrinho ainda não tem e-mail identificado.');if(!confirm('Enviar lembrete para '+c.customer_email+'?'))return;const{data,error}=await supabaseClient.functions.invoke('send-cart-reminder',{body:{cart_id:id}});if(error)return alert(error.message);if(!data?.ok)return alert(data?.error||'Não foi possível enviar.');alert('Lembrete enviado para '+data.recipient+' ♡');loadCarts()};
let n=0,t=setInterval(()=>{n++;if(ensure()||n>60)clearInterval(t)},100);
})();