const $=id=>document.getElementById(id);const cmoney=v=>(Number(v)||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});let currentCustomer=null;
function msg(id,text,bad=false){const e=$(id);if(e){e.textContent=text;e.style.color=bad?'#a33':'#684274'}}
function showAuth(kind,btn){document.querySelectorAll('.auth-tabs .chip').forEach(x=>x.classList.remove('active'));btn?.classList.add('active');$('loginForm').style.display=kind==='login'?'block':'none';$('signupForm').style.display=kind==='signup'?'block':'none';msg('authMsg','')}
async function customerLogin(e){e.preventDefault();msg('authMsg','Entrando...');const {error}=await supabaseClient.auth.signInWithPassword({email:$('customerEmail').value.trim(),password:$('customerPassword').value});if(error)return msg('authMsg',error.message,true);await initCustomer()}
async function customerSignup(e){e.preventDefault();msg('authMsg','Criando sua conta...');const {data,error}=await supabaseClient.auth.signUp({email:$('signupEmail').value.trim(),password:$('signupPassword').value,options:{data:{full_name:$('signupName').value.trim()},emailRedirectTo:'https://lopherastore.com.br/conta.html'}});if(error)return msg('authMsg',error.message,true);if(!data.session)return msg('authMsg','Conta criada ♡ Confira seu e-mail para confirmar o cadastro.');await initCustomer()}
async function resetPassword(){const email=prompt('Digite seu e-mail cadastrado:');if(!email)return;const {error}=await supabaseClient.auth.resetPasswordForEmail(email,{redirectTo:'https://lopherastore.com.br/conta.html'});msg('authMsg',error?error.message:'Enviamos o link de recuperação para seu e-mail ♡',!!error)}
async function customerLogout(){await supabaseClient.auth.signOut();location.reload()}
function showAccountTab(tab,btn){document.querySelectorAll('.account-tab').forEach(x=>x.classList.remove('active'));btn?.classList.add('active');['orders','profile'].forEach(x=>$('account-'+x).style.display=x===tab?'block':'none')}
async function loadProfile(){const {data,error}=await supabaseClient.from('customer_profiles').select('*').eq('user_id',currentCustomer.id).maybeSingle();if(error)return;const p=data||{};$('helloName').textContent=(p.full_name||currentCustomer.email||'cliente').split(' ')[0];const map={profileName:'full_name',profilePhone:'phone',profileBirth:'birth_date',profileCpf:'cpf',profileZip:'zip_code',profileAddress:'address',profileNumber:'address_number',profileComplement:'complement',profileNeighborhood:'neighborhood',profileCity:'city',profileState:'state',profileReference:'reference_point'};Object.entries(map).forEach(([id,k])=>$(id).value=p[k]||'')}
async function saveProfile(e){e.preventDefault();const payload={user_id:currentCustomer.id,full_name:$('profileName').value.trim(),phone:$('profilePhone').value.trim(),birth_date:$('profileBirth').value||null,cpf:$('profileCpf').value.trim(),zip_code:$('profileZip').value.trim(),address:$('profileAddress').value.trim(),address_number:$('profileNumber').value.trim(),complement:$('profileComplement').value.trim(),neighborhood:$('profileNeighborhood').value.trim(),city:$('profileCity').value.trim(),state:$('profileState').value.trim().toUpperCase(),reference_point:$('profileReference').value.trim(),updated_at:new Date().toISOString()};const {error}=await supabaseClient.from('customer_profiles').upsert(payload,{onConflict:'user_id'});msg('profileMsg',error?error.message:'Dados salvos com sucesso ♡',!!error);if(!error)loadProfile()}
const statusLabel={aguardando_atendimento:'Aguardando atendimento',aguardando_pagamento:'Aguardando pagamento',pagamento_confirmado:'Pagamento confirmado',pago:'Pago',emitido_nota:'Nota fiscal emitida',em_producao:'Em produção',preparando_envio:'Preparando envio',enviado:'Enviado',em_transporte:'Em transporte',saiu_para_entrega:'Saiu para entrega',entregue:'Entregue',cancelado:'Cancelado',pagamento_falhou:'Pagamento falhou',reembolsado:'Reembolsado'};
async function loadOrders(){const {data,error}=await supabaseClient.from('orders').select('*,order_items(*)').eq('customer_id',currentCustomer.id).order('created_at',{ascending:false});if(error){$('ordersList').innerHTML='<div class="empty">Não foi possível carregar os pedidos.</div>';return}const list=data||[];$('ordersList').innerHTML=list.length?list.map(o=>`<article class="order-card"><div class="order-top"><div><div class="order-number">PEDIDO #${o.id} · ${new Date(o.created_at).toLocaleDateString('pt-BR')}</div><b>${cmoney(o.total)}</b></div><span class="order-status">${statusLabel[o.status]||o.status}</span></div><div class="order-items">${(o.order_items||[]).map(i=>`<div class="order-item">${i.image_url?`<img src="${i.image_url}">`:''}<div><b>${i.product_name}</b><br>${[i.color,i.size].filter(Boolean).join(' · ')} · ${i.quantity}x · ${cmoney(i.unit_price)}${o.status==='entregue'?`<div class="review-action" id="review_action_${i.id}"><button class="btn" type="button" onclick="openReviewForm(${i.id},'${String(i.product_name||'Produto').replace(/'/g,"\\'")}')">★ Avaliar produto</button></div>`:''}</div></div>`).join('')}</div>${o.invoice_number?`<div class="tracking"><b>Nota fiscal:</b> ${o.invoice_number}${o.invoice_url?` · <a href="${o.invoice_url}" target="_blank">Ver nota ↗</a>`:''}</div>`:''}${o.tracking_code?`<div class="tracking"><b>Rastreio:</b> ${o.tracking_code}${o.tracking_url?` · <a href="${o.tracking_url}" target="_blank">Acompanhar entrega ↗</a>`:''}</div>`:''}</article>`).join(''):'<div class="empty">Você ainda não tem pedidos por aqui ♡</div>'}
async function openReviewForm(orderItemId,productName){
  const holder=$('review_action_'+orderItemId);if(!holder)return;
  const {data:existing}=await supabaseClient.from('product_reviews').select('rating,title,comment').eq('order_item_id',orderItemId).maybeSingle();
  holder.innerHTML='<div class="review-form"><b>Avaliar '+String(productName||'produto')+'</b><label>Nota<select id="rv_rating_'+orderItemId+'"><option value="5">★★★★★ · Amei</option><option value="4">★★★★☆ · Muito bom</option><option value="3">★★★☆☆ · Bom</option><option value="2">★★☆☆☆ · Poderia melhorar</option><option value="1">★☆☆☆☆ · Não gostei</option></select></label><label>Título<input id="rv_title_'+orderItemId+'" maxlength="80" placeholder="Resuma sua experiência"></label><label>Comentário<textarea id="rv_comment_'+orderItemId+'" maxlength="1000" placeholder="Conte o que achou do produto"></textarea></label><button class="btn solid" type="button" onclick="submitReview('+orderItemId+')">Publicar avaliação</button><div id="rv_msg_'+orderItemId+'" class="review-success"></div></div>';
  if(existing){$('rv_rating_'+orderItemId).value=existing.rating||5;$('rv_title_'+orderItemId).value=existing.title||'';$('rv_comment_'+orderItemId).value=existing.comment||''}
}
async function submitReview(orderItemId){
  const m=$('rv_msg_'+orderItemId);m.textContent='Publicando…';
  const {error}=await supabaseClient.rpc('submit_product_review',{p_order_item_id:orderItemId,p_rating:Number($('rv_rating_'+orderItemId).value),p_title:$('rv_title_'+orderItemId).value,p_comment:$('rv_comment_'+orderItemId).value});
  if(error){m.textContent=error.message;return}
  m.textContent='Avaliação publicada ♡ Obrigada por contar sua experiência!';
}
window.openReviewForm=openReviewForm;window.submitReview=submitReview;
async function initCustomer(){const {data:{user}}=await supabaseClient.auth.getUser();currentCustomer=user;if(!user){$('authView').style.display='grid';$('accountView').style.display='none';return}$('authView').style.display='none';$('accountView').style.display='block';await Promise.all([loadProfile(),loadOrders()])}
document.addEventListener('DOMContentLoaded',initCustomer);