/* Lophera Store — chat V4: produtos, carrinho e imagens */
(function(){
 if(window.__lopheraChatV4Loaded)return; window.__lopheraChatV4Loaded=true;
 const $=id=>document.getElementById(id), safe=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
 const money=v=>(Number(v)||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
 const KEY='lophera_chat_meta'; let meta=null,poll=null,busy=false,opened=false,pendingShare=null;
 function readMeta(){try{const m=JSON.parse(localStorage.getItem(KEY)||'null');if(m?.id&&m?.token)return m}catch(_){}const m={id:crypto.randomUUID(),token:crypto.randomUUID(),name:'',email:''};localStorage.setItem(KEY,JSON.stringify(m));return m}
 function saveMeta(){localStorage.setItem(KEY,JSON.stringify(meta))}
 function time(i){try{return new Date(i).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}catch(_){return''}}
 function css(){if($('lophera-chat-style'))return;const s=document.createElement('style');s.id='lophera-chat-style';s.textContent=`
 .lp-chat-launch{position:fixed;right:22px;bottom:22px;z-index:990;width:58px;height:58px;border:0;border-radius:50%;background:#6c3f7d;color:#fff;box-shadow:0 12px 35px #3b244c42;cursor:pointer;font-size:23px;display:grid;place-items:center}
 .lp-chat-panel{position:fixed;right:22px;bottom:92px;z-index:991;width:min(390px,calc(100vw - 28px));height:min(620px,calc(100vh - 115px));background:#fff;border:1px solid #dccfe1;border-radius:18px;box-shadow:0 24px 70px #28152f38;display:none;overflow:hidden;font-family:Montserrat,Arial,sans-serif}.lp-chat-panel.open{display:grid;grid-template-rows:auto 1fr auto}
 .lp-chat-head{background:#302333;color:#fff;padding:16px 18px;display:flex;align-items:center;gap:12px}.lp-chat-brand{width:38px;height:38px;border-radius:50%;background:#f3e8f6;color:#5f3970;display:grid;place-items:center;font:600 18px 'Cormorant Garamond',serif}.lp-chat-head b{display:block;font:600 18px 'Cormorant Garamond',serif}.lp-chat-head small{display:block;font-size:9px;opacity:.72}.lp-chat-close{margin-left:auto;border:0;background:transparent;color:#fff;font-size:22px;cursor:pointer}
 .lp-chat-body{overflow:auto;padding:15px;background:#fbf8fc}.lp-chat-welcome{height:100%;display:grid;place-items:center;text-align:center;padding:18px}.lp-chat-welcome-inner{max-width:280px}.lp-chat-heart{font:44px 'Cormorant Garamond',serif;color:#7b4a8a}.lp-chat-welcome h3{font:500 25px 'Cormorant Garamond',serif;margin:3px 0 8px}.lp-chat-welcome p{font-size:10px;line-height:1.7;color:#746778}.lp-chat-welcome input{width:100%;padding:11px;border:1px solid #d9cbdc;margin:5px 0;border-radius:8px}.lp-chat-welcome .btn{width:100%;margin-top:8px;border-radius:8px}
 .lp-chat-msgs{display:flex;flex-direction:column;gap:9px}.lp-chat-msg{display:block;width:max-content;max-width:84%;height:auto;flex:0 0 auto;padding:9px 11px;border-radius:13px;font-size:11px;line-height:1.55;word-break:break-word}.lp-chat-msg.from-customer{align-self:flex-end;background:#6c3f7d;color:#fff;border-bottom-right-radius:4px}.lp-chat-msg.from-admin{align-self:flex-start;background:#fff;border:1px solid #e1d7e4;color:#3f3342;border-bottom-left-radius:4px}.lp-chat-msg small{display:block;font-size:7px;opacity:.62;margin-top:4px;text-align:right}
 .lp-chat-image{display:block;max-width:230px;max-height:230px;border-radius:10px;margin:2px 0 5px;object-fit:cover;cursor:pointer}.lp-chat-card{width:250px;max-width:100%;background:#fff;color:#3f3342;border:1px solid #dfd3e3;border-radius:10px;overflow:hidden;margin:3px 0}.lp-chat-card img{width:100%;height:120px;object-fit:cover}.lp-chat-card-body{padding:10px}.lp-chat-card b{display:block;font-size:11px}.lp-chat-card span{display:block;font-size:9px;color:#756879;margin-top:3px}.lp-chat-cart-item{padding:5px 0;border-bottom:1px solid #eee6ef;font-size:9px}.lp-chat-card .lp-mini-link{display:inline-block;margin-top:8px;color:#6c3f7d;font-weight:600}
 .lp-chat-compose{border-top:1px solid #eadfec;background:#fff;padding:9px}.lp-chat-actions{display:flex;gap:6px;margin-bottom:7px;overflow:auto}.lp-chat-actions button{white-space:nowrap;border:1px solid #d9cbdc;background:#fff;color:#664273;border-radius:99px;padding:7px 9px;font-size:8px;cursor:pointer}.lp-chat-compose-row{display:grid;grid-template-columns:38px 1fr 44px;gap:7px}.lp-chat-attach,.lp-chat-send{border:0;border-radius:10px;background:#efe4f2;color:#653d72;cursor:pointer;font-size:17px}.lp-chat-send{background:#6c3f7d;color:#fff}.lp-chat-compose textarea{resize:none;min-height:42px;max-height:95px;border:1px solid #d9cbdc;border-radius:10px;padding:10px;font:11px Montserrat,Arial,sans-serif;outline:none}.lp-chat-error{color:#9b3d57;font-size:9px;margin-top:5px;min-height:12px}.lp-chat-uploading{font-size:8px;color:#725b79;margin:3px 0}.lp-chat-empty{text-align:center;color:#8a7b8f;font-size:10px;padding:36px 15px}
 @media(max-width:560px){.lp-chat-launch{right:14px;bottom:14px}.lp-chat-panel{right:14px;bottom:82px;height:min(590px,calc(100vh - 105px))}}
 `;document.head.appendChild(s)}
 function shell(){if($('lopheraChatPanel'))return;document.body.insertAdjacentHTML('beforeend',`
 <button class="lp-chat-launch" id="lopheraChatLaunch" aria-label="Abrir atendimento">💬</button>
 <section class="lp-chat-panel" id="lopheraChatPanel"><div class="lp-chat-head"><div class="lp-chat-brand">L</div><div><b>Lophera ♡</b><small>Fale com a gente</small></div><button class="lp-chat-close" id="lopheraChatClose">×</button></div><div class="lp-chat-body" id="lopheraChatBody"></div><div class="lp-chat-compose" id="lopheraChatCompose" style="display:none"><div class="lp-chat-actions"><button onclick="lopheraChatShareCart()">🛒 Enviar meu carrinho</button><button onclick="lopheraChatCheckout()">✓ Finalizar compra</button></div><div class="lp-chat-uploading" id="lopheraChatUploadStatus"></div><div class="lp-chat-compose-row"><button class="lp-chat-attach" id="lopheraChatAttach" title="Enviar imagem">📎</button><input id="lopheraChatFile" type="file" accept="image/png,image/jpeg,image/webp" hidden><textarea id="lopheraChatInput" maxlength="1500" placeholder="Digite sua mensagem…"></textarea><button class="lp-chat-send" id="lopheraChatSend">➤</button></div><div class="lp-chat-error" id="lopheraChatError"></div></div></section>`);
 $('lopheraChatLaunch').onclick=()=>toggle();$('lopheraChatClose').onclick=()=>toggle(false);$('lopheraChatSend').onclick=sendText;$('lopheraChatAttach').onclick=()=>$('lopheraChatFile').click();$('lopheraChatFile').onchange=sendImage;$('lopheraChatInput').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendText()}}}
 async function accountInfo(){try{const{data:{session}}=await supabaseClient.auth.getSession();if(!session)return{};const{data:p}=await supabaseClient.from('customer_profiles').select('full_name').eq('user_id',session.user.id).maybeSingle();return{name:p?.full_name||session.user.user_metadata?.full_name||'',email:session.user.email||''}}catch(_){return{}}}
 async function ensureThread(force=false){meta=meta||readMeta();const a=await accountInfo();if(a.name&&!meta.name)meta.name=a.name;if(a.email&&!meta.email)meta.email=a.email;saveMeta();if(!force&&!meta.name&&!meta.email)return false;const{data,error}=await supabaseClient.rpc('open_chat_thread',{p_thread_id:meta.id,p_client_token:meta.token,p_name:meta.name||null,p_email:meta.email||null});if(error)throw error;return!!data?.id}
 function welcome(){$('lopheraChatCompose').style.display='none';$('lopheraChatBody').innerHTML=`<div class="lp-chat-welcome"><div class="lp-chat-welcome-inner"><div class="lp-chat-heart">♡</div><h3>Oii! Como podemos ajudar?</h3><p>Deixe seu primeiro nome para começar. O e-mail é opcional.</p><input id="lpChatName" maxlength="80" placeholder="Seu nome"><input id="lpChatEmail" maxlength="160" type="email" placeholder="Seu e-mail (opcional)"><button class="btn solid" id="lpChatStart">Começar conversa</button><div class="lp-chat-error" id="lpChatStartError"></div></div></div>`;$('lpChatName').value=meta?.name||'';$('lpChatEmail').value=meta?.email||'';$('lpChatStart').onclick=start}
 async function start(){const n=$('lpChatName').value.trim(),e=$('lpChatEmail').value.trim(),err=$('lpChatStartError');if(!n){err.textContent='Conta seu primeiro nome pra gente ♡';return}if(e&&!/^\S+@\S+\.\S+$/.test(e)){err.textContent='Confira o e-mail.';return}meta.name=n;meta.email=e;saveMeta();try{await ensureThread(true);await loadMessages();await flushPending();startPoll()}catch(x){err.textContent=x?.message||'Não foi possível abrir o chat.'}}
 async function mediaUrls(rows){const paths=[...new Set(rows.map(x=>x.attachment_path).filter(Boolean))];if(!paths.length)return{};const{data}=await supabaseClient.functions.invoke('chat-media',{body:{action:'view',thread_id:meta.id,client_token:meta.token,paths}});return data?.urls||{}}
 function contextHtml(m){const p=m.context_payload||{};if(m.context_type==='product'){return `<div class="lp-chat-card">${p.image?'<img src="'+safe(p.image)+'">':''}<div class="lp-chat-card-body"><b>${safe(p.name||'Produto Lophera')}</b><span>${safe([p.color,p.size].filter(Boolean).join(' · '))}</span><span>${money(p.price)}</span>${p.url?'<a class="lp-mini-link" href="'+safe(p.url)+'">Ver produto ↗</a>':''}</div></div>`}if(m.context_type==='cart'){const items=Array.isArray(p.items)?p.items:[];return `<div class="lp-chat-card"><div class="lp-chat-card-body"><b>🛒 Carrinho da Lophera</b>${items.slice(0,8).map(i=>'<div class="lp-chat-cart-item">'+safe(i.name)+' · '+safe([i.color,i.size].filter(Boolean).join(' · '))+' · '+Number(i.qty||1)+' un.</div>').join('')}<span><b>Total: ${money(p.total)}</b></span><a class="lp-mini-link" href="checkout.html">Finalizar compra ↗</a></div></div>`}return''}
 async function loadMessages(){if(!meta?.id)return;const{data,error}=await supabaseClient.rpc('get_chat_messages',{p_thread_id:meta.id,p_client_token:meta.token});if(error)throw error;const rows=Array.isArray(data)?data:[],urls=await mediaUrls(rows);$('lopheraChatCompose').style.display='block';$('lopheraChatBody').innerHTML=rows.length?'<div class="lp-chat-msgs">'+rows.map(m=>'<div class="lp-chat-msg '+(m.sender==='admin'?'from-admin':'from-customer')+'">'+contextHtml(m)+(m.attachment_path&&urls[m.attachment_path]?'<a href="'+safe(urls[m.attachment_path])+'" target="_blank"><img class="lp-chat-image" src="'+safe(urls[m.attachment_path])+'" alt="'+safe(m.attachment_name||'Imagem')+'"></a>':'')+(m.body?safe(m.body):'')+'<small>'+time(m.created_at)+'</small></div>').join('')+'</div>':'<div class="lp-chat-empty">Pode mandar sua mensagem 💜</div>';const b=$('lopheraChatBody');b.scrollTop=b.scrollHeight}
 async function sendV2(o){await ensureThread(true);const{data,error}=await supabaseClient.rpc('send_chat_message_v2',{p_thread_id:meta.id,p_client_token:meta.token,p_body:o.body||'',p_attachment_path:o.path||null,p_attachment_name:o.name||null,p_attachment_mime:o.mime||null,p_context_type:o.type||null,p_context_payload:o.payload||null});if(error||!data?.ok)throw error||new Error('Não foi possível enviar.');await loadMessages()}
 async function sendText(){if(busy)return;const i=$('lopheraChatInput'),body=i.value.trim();if(!body)return;busy=true;try{await sendV2({body});i.value=''}catch(e){$('lopheraChatError').textContent=e?.message||'Erro ao enviar.'}finally{busy=false}}
 async function sendImage(){const f=$('lopheraChatFile').files?.[0];if(!f)return;const st=$('lopheraChatUploadStatus');if(!['image/png','image/jpeg','image/webp'].includes(f.type)){st.textContent='Use PNG, JPG ou WEBP.';return}if(f.size>8*1024*1024){st.textContent='A imagem pode ter até 8 MB.';return}try{st.textContent='Enviando imagem…';await ensureThread(true);const{data,error}=await supabaseClient.functions.invoke('chat-media',{body:{action:'upload',thread_id:meta.id,client_token:meta.token,content_type:f.type}});if(error||!data?.ok)throw new Error(data?.error||error?.message);const up=await supabaseClient.storage.from('chat-media').uploadToSignedUrl(data.path,data.token,f,{contentType:f.type});if(up.error)throw up.error;await sendV2({body:'',path:data.path,name:f.name,mime:f.type});st.textContent='';$('lopheraChatFile').value=''}catch(e){st.textContent=e?.message||'Não foi possível enviar a imagem.'}}
 async function shareCart(){const c=JSON.parse(localStorage.getItem('lophera_test_cart')||'[]');if(!c.length){alert('Seu carrinho está vazio ♡');return}const payload={items:c.map(x=>({name:x.name,color:x.color,size:x.size,qty:x.qty,price:x.price})),total:c.reduce((a,x)=>a+Number(x.price||0)*Number(x.qty||1),0)};await openShare({type:'cart',body:'Quero tirar uma dúvida sobre este carrinho:',payload})}
 async function openShare(x){pendingShare=x;await toggle(true);await flushPending()}
 async function flushPending(){if(!pendingShare||!meta?.name&&!meta?.email)return;const x=pendingShare;pendingShare=null;try{await sendV2(x)}catch(e){pendingShare=x;$('lopheraChatError').textContent=e?.message||'Não foi possível enviar.'}}
 async function toggle(force){const p=$('lopheraChatPanel');opened=typeof force==='boolean'?force:!p.classList.contains('open');p.classList.toggle('open',opened);if(!opened){clearInterval(poll);return}meta=readMeta();try{const ok=await ensureThread(false);if(ok){await loadMessages();await flushPending();startPoll()}else welcome()}catch(_){welcome()}}
 function startPoll(){clearInterval(poll);poll=setInterval(()=>{if(opened)loadMessages().catch(()=>{})},6000)}
 window.lopheraChatShareProduct=async p=>openShare({type:'product',body:'Quero tirar uma dúvida sobre este produto:',payload:p});
 window.lopheraChatShareCart=shareCart;window.lopheraChatCheckout=async()=>{const c=JSON.parse(localStorage.getItem('lophera_test_cart')||'[]');if(!c.length)return alert('Seu carrinho está vazio ♡');const{data:{session}}=await supabaseClient.auth.getSession();location.href=session?'checkout.html':'conta.html'};
 function init(){if(typeof supabaseClient==='undefined')return;css();shell();meta=readMeta()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();